### ISSUE TITLE
Move NFD repo to kubernetes-sigs organization

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#175]
The incubator process has been deprecated and has been superseded by Kubernetes subprojects. The NFD repository could possibly be moved under the [Kubernetes-SIGs organization](http://github.com/kubernetes-sigs/). This was discussed in [SIG-node meeting](https://docs.google.com/document/d/1Ne57gvidMEWXR70OxxnRkYquAoMpt56o75oZtg-OeBg/edit) on 2018/10/09 and we got a green light there.

Tasks to do and questions to resolve:
- [x] decide on the label namespace to use instead of `node.alpha.kubernetes-incubator.io` (#176)
- [x] decide where (registry/repo) to host images (#177)
- [x] create a request to move the repo (kubernetes/org#172)
- [x] request membership in kubernetes-sigs organization (kubernetes/org#174)
- [x] enable bots in the new repo (CNCF CLA bot, merge bot, Kubernetes PR bots)
- [x] add `k8s-sig-node` topic to the new repo
- [x] change import paths in the source code from `github.com/kubernetes-incubator/node-feature-discovery` to `sigs.k8s.io/node-feature-discovery` (#191)
- [x] change documentation (e.g. README) to point to the new repository (#190)

**Comment by marquiz** [comment]
Working on #177 to be able to finally close this issue

**Comment by marquiz** [comment]
We'll soon be able to tick the last checkbox.

/remove-lifecycle stale

**Comment by marquiz** [comment]
#177 closed. In addition to serving image from the new registry, all CI has now been migrated from TravisCI to Kubernetes test-infra.

Closing this, finally! 🎉
