### ISSUE TITLE
Release v0.9.0

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#565]
## Release Checklist

- [x] All [OWNERS](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/OWNERS) must LGTM the release proposal
- [x] Verify that the changelog in this issue is up-to-date
- [x] For major releases (v0.$MAJ.0), an OWNER creates a release branch with
      `git branch release-0.$MAJ master`
- [ ] Prepare `release-0.$MAJ` release branch
  - [x] An OWNER creates a vanilla release branch from master and pushes it with
        `git push release-0.$MAJ`
  - [x] Run `scripts/prepare-release.sh $VERSION` to turn references to point to the upcoming release
        (README, deployment templates, docs configuration, test/e2e flags), submit a PR agains the release branch
  - An OWNER prepares a draft release
    - [x] Create a draft release at [Github releases page](https://github.com/kubernetes-sigs/node-feature-discovery/releases)
    - [x] Write the change log into the draft release
    - [x] Upload release artefacts generated by `prepare-release.sh` script above to the draft release
  - [x] An OWNER runs
       `git tag -s $VERSION`
        and inserts the changelog into the tag description.
- [x] An OWNER pushes the tag with
      `git push $VERSION`
  - Triggers prow to build and publish a staging container image
      `gcr.io/k8s-staging-nfd/node-feature-discovery:$VERSION`
  - Triggers build of the documentation and publish it at
        https://kubernetes-sigs.github.io/node-feature
- [x] Submit a PR against [k8s.io](https://github.com/kubernetes/k8s.io), updating `k8s.gcr.io/images/k8s-staging-nfd/images.yaml` to promote the container images (both "full" and "minimal" variants) to production
- [x] Wait for the PR to be merged and verify that the image (`k8s.gcr.io/nfd/node-feature-discovery:$VERSION`) is available.
- [x] Publish the draft release prepared at the [Github releases page](https://github.com/kubernetes-sigs/node-feature-discovery/releases)
      which will also trigger a Helm repo index update to add the latest release
- [x] Add a link to the tagged release in this issue.
- [x] Send an announcement email to `kubernetes-dev@googlegroups.com` with the subject `[ANNOUNCE] node-feature-discovery $VERSION is released`
- [x] Add a link to the release announcement in this issue
- [x] For a major release (or a point release of the latest major release), update README in master branch
  - [x] Update references e.g. by running `scripts/prepare-release.sh $VERSION` but **only** committing README.md, and,
        submit a PR
  - [x] Wait for the PR to be merged
- [x] For a major release, create an unannotated *devel* tag in the master branch, on the first commit that gets merged after the release branch has been created (presumably the README update commit above), and, push the tag:
      `DEVEL=v0.$(($MAJ+1)).0-devel; git tag $DEVEL master && git push $DEVEL`
      This ensures that the devel builds on the master branch will have a meaningful version number.
- [x] Close this issue

## Roadmap

[Github milestone v0.9.0](https://github.com/kubernetes-sigs/node-feature-discovery/milestone/3)

### Switch over to kustomize

NFD now leverages kustomize for kubectl based deployments, making it easier to manage user-specific customized deployment scenarios. See [deployment with kustomize](https://kubernetes-sigs.github.io/node-feature-discovery/v0.9/get-started/deployment-and-usage.html#deployment-with-kustomize) in the documentation for more details.

### Feature label sub-namespaces

NFD now allow the usage of sub-namespaces of the default label namespace for easier separation of vendor or application specific labels. That is, e.g. `<vendor>.feature.node.kubernetes.io` is available without any extra configuration.

### TLS: accept client certs based on SAN

NFD now does client certificate verification based on SAN (Subject Alternative Name) in addition to Common Name (CN). This makes the virtually broken `--verify-node-name` option usable again.

### Readiness and liveliness probes to nfd-master

The default kustomize and Helm deployments now enable gRPC-based readiness and liveness probes for the nfd-master containers.

### Miscellaneous

- Support matching against USB device serial number in the custom feature source (#521)
- Various fixes and improvements to Helm chart deployment
- Configurable base image for manual builds (#513)
- Make nost /usr/lib and /usr/src available for nfd-worker (#519)
- Correct the names of SSE4* cpuid flags (#547)
- Detect AVX512 FP16 (#555)

### List of PRs

- scripts/update-gh-pages: fix helm repo update (#486)
- github: two more steps to release process (#488)
- README: update references to version 0.8.0 (#490)
- github: update gh-pages on published releases (#489)
- docs: describe Helm repo as the primary option for Helm (#491)
- Docs: Add Table header to master/worker chart parameters (#492)
- scripts/update-gh-pages: slightly cleaner log output (#494)
- [helm] fix nfd worker tolerations value (#495)
- bump  Go  to 1.16 (#497)
- Helm chart: Fix configMap indenting (#496)
- scripts/prepare-release: option to only create assets (#502)
- README: update references to version 0.8.1 (#507)
- Update deps (#499)
- github: add a reminder about both image variants in the release process (#506)
- github: update release process to create a 'devel' tag (#498)
- docs: fixes in Helm documentation (#509)
- Add support for configurable runtime full and minimal images. (#513)
- Accept client certs based on SAN, not just CN (#514)
- helm: add extraLabelNs master flag (#515)
- Mount /usr inside the Pod (#519)
- Add support for using USB device serial number (#521)
- README: update references to v0.8.2 (#531)
- docs: show full version number in sidebar (#532)
- utils/dump: do not print empty header line (#542)
- source: define source names as consts (#544)
- cpuid: correct the name of SSE4* cpuid flags (#547)
- go.mod: update dependencies (#546)
- make go report happy (#538)
- chore: update tolerations and affinities to control-plane (#537)
- Straighten wrinkles in lint fixes (#551)
- go.mod: update to klauspost/cpuid/v2@v2.0.9 (#555)
- Makefile: add apigen target (#541)
- Makefile: add lint target (#549)
- Remove wrong comands on documentation (#559)
- nfd-master: allow sub-namespaces of the default label ns (#536)
- helm: add readme (#564)
- Dockerfile: update go to 1.16.7 (#568)
- go.mod: update kubernetes to v1.22.0 (#569)
- Move to kustomize (#573)
- Better error reporting of kernel and cpu feature sources (#570)
- Add Readiness and liveliness probes to nfd-master (#563)
- cstate/pstate: Skip check on non intel arches (#571)
- docs: clarify the cpu.cstate feature (#572)
- scripts: fix prepare-release.sh to update all kustomize files (#577)
- kustomize: fix broken master-worker-combined base (#578)

**Comment by adrianchiris** [comment]
looking at, Github milestone v0.9.0

are #523 #558 planned for v0.9.0 ?

**Comment by marquiz** [comment]
#558 yes, via #398

I wasn't planning on pending #523

**Comment by adrianchiris** [comment]
ack :) 
/lgtm

**Comment by ArangoGutierrez** [comment]
Could we also fit into `v0,9.0` this PR https://github.com/kubernetes-sigs/node-feature-discovery/pull/563 ? I am working on the requested changes ASAP

**Comment by marquiz** [comment]
> Could we also fit into `v0,9.0` this PR #563 ? I am working on the requested changes ASAP

Sure, if you're working on that. Added #522 to the milestone.

**Comment by marquiz** [comment]
ping @zvonkok @Ethyling, anything to add?

Planning to cut a release already this week

**Comment by ArangoGutierrez** [comment]
@marquiz CHANGELOG needs to be updated I guess

**Comment by marquiz** [comment]
> @marquiz CHANGELOG needs to be updated I guess

Yup, now updated.

**Comment by marquiz** [comment]
Release page in Github:
https://github.com/kubernetes-sigs/node-feature-discovery/releases/tag/v0.9.0

**Comment by marquiz** [comment]
Done here
/close
