### ISSUE TITLE
Release v0.10.0

### ISSUE THREAD

**Issue by marquiz** [kubernetes-sigs/node-feature-discovery#678]
## Release Checklist

- [x] All [OWNERS](https://github.com/kubernetes-sigs/node-feature-discovery/blob/master/OWNERS) must LGTM the release proposal
- [x] Verify that the changelog in this issue is up-to-date
- [x] For major releases (v0.$MAJ.0), an OWNER creates a release branch with
      `git branch release-0.$MAJ master`
- [ ] Prepare `release-0.$MAJ` release branch
  - [x] An OWNER creates a vanilla release branch from master and pushes it with
        `git push release-0.$MAJ`
  - [x] Run `scripts/prepare-release.sh $VERSION` to turn references to point to the upcoming release
        (README, deployment templates, docs configuration, test/e2e flags), submit a PR agains the release branch
  - An OWNER prepares a draft release
    - [x] Create a draft release at [Github releases page](https://github.com/kubernetes-sigs/node-feature-discovery/releases)
    - [x] Write the change log into the draft release
    - [x] Upload release artefacts generated by `prepare-release.sh` script above to the draft release
  - [x] An OWNER runs
       `git tag -s $VERSION`
        and inserts the changelog into the tag description.
- [x] An OWNER pushes the tag with
      `git push $VERSION`
  - Triggers prow to build and publish a staging container image
      `gcr.io/k8s-staging-nfd/node-feature-discovery:$VERSION`
  - Triggers build of the documentation and publish it at
        https://kubernetes-sigs.github.io/node-feature
- [x] Submit a PR against [k8s.io](https://github.com/kubernetes/k8s.io), updating `k8s.gcr.io/images/k8s-staging-nfd/images.yaml` to promote the container images (both "full" and "minimal" variants) to production
- [x] Wait for the PR to be merged and verify that the image (`k8s.gcr.io/nfd/node-feature-discovery:$VERSION`) is available.
- [x] Publish the draft release prepared at the [Github releases page](https://github.com/kubernetes-sigs/node-feature-discovery/releases)
      which will also trigger a Helm repo index update to add the latest release
- [x] Add a link to the tagged release in this issue.
- [x] Send an announcement email to `kubernetes-dev@googlegroups.com` with the subject `[ANNOUNCE] node-feature-discovery $VERSION is released`
- [x] Add a link to the release announcement in this issue
- [ ] For a major release (or a point release of the latest major release), update README in master branch
  - [ ] Update references e.g. by running `scripts/prepare-release.sh $VERSION` but **only** committing README.md, and,
        submit a PR
  - [ ] Wait for the PR to be merged
- [ ] For a major release, create an unannotated *devel* tag in the master branch, on the first commit that gets merged after the release branch has been created (presumably the README update commit above), and, push the tag:
      `DEVEL=v0.$(($MAJ+1)).0-devel; git tag $DEVEL master && git push $DEVEL`
      This ensures that the devel builds on the master branch will have a meaningful version number.
- [ ] Close this issue

### Expression-based custom label rules

We implemented new expression-based format for writing labeling rules, greatly expanding the capabilities for vendor and application specific labeling. It covers much more features than the built-in labels reveal, supports tempating and more. See new [customization guide](https://kubernetes-sigs.github.io/node-feature-discovery/v0.10/advanced/customization-guide.html#label-rule-format) for more details.

### NodeFeatureRule custom resource

We introduce new NodeFeatureRule custom resource, enabling the deployment vendor and application specific labeling rules as Kubernetes API objects. See [customization guide](https://kubernetes-sigs.github.io/node-feature-discovery/v0.10/advanced/customization-guide.html#nodefeaturerule-custom-resource) for details.

### Detection of network, storage and nvdimm devices

NFD now discovers network, block storage and nvdimm devices. No new built-in labels are introduced but the device information is available for custom label rules to use. See [available features](https://kubernetes-sigs.github.io/node-feature-discovery/v0.10/advanced/customization-guide.html#available-features) for details.

### Topology-updater daemon

NFD-Topology-Updater is a new daemon that advertises topology of available and allocatable system resources via NodeResourceTopology custom resources. See the [documentation](https://kubernetes-sigs.github.io/node-feature-discovery/v0.10/get-started/introduction.html#nfd-topology-updater) for more details.

### New profile label namespace 

NFD now by default allows a new `profile.node.kubernetes.io` label namespace (and it's sub-namespaces). This can be used in custom labels and is intended for vendor or application specific higher level "meta features".

### Label names from the local source changed

NFD stopped injecting the filename of the hook/featurefile into the name of the label.

NOTE: This breaks backwards compatibility with usage scenarios that rely on implicitly prefixing the label with the filename. However, we felt that the somewhat confusing and counter-intuitive behavior needs to be changed. The suggested way to fix existing use cases is to user fully namespaced `<namespace>/<name>=<value>` format (this will retain compatibility with older versions of NFD).

### TLS and cert-manager integration in Helm chart

NFD Helm chart now supports enabling TLS and [cert-manager](https://cert-manager.io/) via the `tls.enable` and `tls.certManager` options. See the [documentation](https://kubernetes-sigs.github.io/node-feature-discovery/v0.10/get-started/deployment-and-usage.html#communication-security-with-tls) for details.

### IOMMU source deprecated

The IOMMU source has been deprecated and is now disabled by default. Thus, it's only feature label `feature.node.kubernetes.io/iommu-enabled` is not available in the default configuration. To enable it, set the `core.labelSources` option to the value `[all, iommu]` in the nfd-worker configuration. See [worker configuration](https://kubernetes-sigs.github.io/node-feature-discovery/v0.10/get-started/deployment-and-usage.html#worker-configuration) for more details on configuring nfd-worker.

NOTE: the `iommu_group/type` is now available as per PCI device attribute to be used for custom label rules. See the [customization guide](https://kubernetes-sigs.github.io/node-feature-discovery/v0.10/advanced/customization-guide.html) for details on using custom label rules.

### Miscellaneous

- /usr/src is not mounted by default, anymore (#585)
- simplify nfd-worker configuration in Helm (#627)
- detect Intel SGX (#647)
- add additional IBM Z CPUID flags (#675)
- nfd-worker config
  - add `core.labelSources` config option, deprecating `core.sources` (#673)
  - add `core.featureSources` config option (#605)
  - disable sources by prefixing with dash ('-') (#670)
- fix kustomize sample overlay enabling cert-manager (#710)

### List of PRs

- README: update deployment instructions to use v0.9.0 (#580)
- nfd-worker: split out gRPC connection handling (#552)
- gitignore: add kustomization.yaml (#583)
- source/custom: refactor kconfig rule internal representation (#543)
- Fix the typo in deployment-and-usage.md (#575)
- Only add kustomization.yaml in the root to .gitignore (#587)
- scripts/test-infra: verify buildability of kustomize overlays (#586)
- deployment: make /usr/src hostpath mount optional (#585)
- nfd-master: allow profile.node.kubernetes.io label ns (#548)
- Fix a link in deployment-and-usage.md (#589)
- Fix broken link for worker-conf example (#590)
- source/network: silence annoying/useless log message (#592)
- source: rename FeatureSource to LabelSource (#596)
- deployment: fix formatting of the worker conf sample (#599)
- source: make sources register themselves (#597)
- Introducing NFD Topology Updater exposing Resource hardware Topology info through CRs (#525)
- source: introduce FeatureSource interface (#601)
- Fix broken link on docs/get-started (#603)
- Utilize go generate (#602)
- Trim single quotes in parseOSRelease (#606)
- docs: remote wip note from worker configuration reference (#611)
- deployment: fix typo in overlay name (#609)
- Update developer-guide.md (#613)
- scripts/test-infra: bump golangci-lint to v1.42.1 (#615)
- docs: fix TOCs (#610)
- deployment: align topologyupdater overlays (#607)
- drop the topology updater job (#622)
- topology-updater:fix klog initialization (#625)
- docs: update dependencies (#624)
- deployment/helm: don't force sleep-interval in  worker cmdline flags (#628)
- Bump to golang v1.17 (#629)
- source: fix gofmt errors (#631)
- Makefile: let gofmt-verify write changes back to files (#632)
- deployment: Simplify NFD worker configuration in Helm (#627)
- deployment: add topology updater helm chart (#623)
- docs: mention minimum required kubectl version (#635)
- Documentation capturing enablement of NFD-Topology-Updater in NFD (#526)
- resourcemonitor: aggregate and provide the memory and hugepages information (#593)
- pkg/resourcemonitor: fix typo in comment (#641)
- pkg/api/feature: small improvements (#642)
- test/e2e: make e2e tests run on single-node cluster (#643)
- test/e2e: drop /boot mount (#644)
- source: implement FeatureSource interface (#604)
- Topology-updater introduction typo fix (#645)
- deployment: Implicitly generate the worker ConfigMap name (#640)
- More topology updater documentation typo fixes (#648)
- source/custom: expression based label rules (#639)
- More extensive and expressive custom rules (#464)
- NFD-Topology-Updater: Bump NRT API to version v0.0.12 (#652)
- grpc: extend the API to send raw features (#646)
-  specify CRD for custom labeling rules (#653)
- source/custom: move rule matching to pkg/apis/nfd (#654)
- pkg/apis/nfd: drop excess field from the CRD (#657)
- Update the link of slack channel (#659)
- Add code for interacting with CRD API (#655)
- deployment: clean up base/topologyupdater-daemonset (#608)
- topologyupdater: logs relevant message when feature-gate is disabled. (#633)
- nfd-master: implement controller for NodeFeatureRule CRs (#656)
- source/storage: implement FeatureSource (#649)
- Revert "test/e2e: drop /boot mount" (#664)
- CRD-based custom node labeling (#553)
- source/network: implement FeatureSource (#660)
- source/memory: implement FeatureSource (#661)
- Templating of custom label names (#550)
- source/cpu: detect Intel SGX (#647)
- source/kernel: don't advertise selinux.enabled=false (#665)
- source/memory: fix memory.numa label (#666)
- pkg/apis/nfd: stricter format checking for template labels (#668)
- Add variables to feature rule spec and support backrefs  (#663)
- source/cpu: add additional IBM Z CPU Flags (#675)
- images: use k8s-staging-test-infra/gcb-docker-gcloud (#685)
- images: fix invalid k8s-staging-test-infra/gcb-docker-gcloud tag (#686)
- Makefile: Add make deploy rule (#679)
- docs: drop cmdline help from developer guide (#672)
- Lint fixes to pkg/apis (#687)
- Add deploy-prune makefile rule to ease devel processes (#667)
- Use single-dash format of cmdline flags (#671)
- source/kernel: ditch regexp in kconfig parsing (#683)
- nfd-worker: rename 'sources' config option (#673)
- source/kernel: drop length check of kconfig values (#682)
- source/kernel: unmangled kconfig values for custom rules  (#684)
- scripts: increase e2e-test image poll timeout to 12mins (#688)
- scripts/test-infra: bump helm to v3.7.1 (#689)
- nfd-worker: disable sources more easily (#670)
- nfd-worker: add core.featureSources config option (#605)
- source: make per-source unit tests stricter (#691)
- source/fake: implement FeatureSource (#692)
- docs: fix mistake in md format (#693)
- test/e2e: revise usage of nfd command line flags (#690)
- source/usb: fix fallback to default label format (#694)
- source/local: log features per each hook and feature file (#696)
- source/local: don't prefix label names with the filename (#695)
- nfd-worker: drop 'custom-' prefix from matchFeatures custom rules (#697)
- Dockerfile: build grpc_health-probe from source (#707)
- Fix readiness and liveness checks (#709)
- Fix kustomization template to work with cert-manager (#710)
- Enable TLS and cert-manager created certs for helm chart (#712)
- deployment/helm: refactor nfd-master rbac parameters (#706)
- deployment/helm: disable nfr controller for parallel instances (#699)
- deployment: use new custom rule format in sample configs (#701)
- source/iommu: deprecate and disable by default  (#677)
- Initial bash at new TLS docs (#713)
- docs: add customization guide (#704)
- docs: small tinkering on the TLS documentation (#714)
- source/pci: add iommu_group/type attribute (#705)
- docs: small fix in block and net features in customization guide (#715)

## TODO:

See [v0.10.0 milestone](https://github.com/kubernetes-sigs/node-feature-discovery/milestone/4)

**Comment by ArangoGutierrez** [comment]
https://github.com/kubernetes/k8s.io/pull/3248

**Comment by ArangoGutierrez** [comment]
```bash
[eduardo@fedora node-feature-discovery]$ skopeo inspect --no-tags  docker://gcr.io/k8s-staging-nfd/node-feature-discovery:v0.10.0
{
    "Name": "gcr.io/k8s-staging-nfd/node-feature-discovery",
    "Digest": "sha256:f2eed733211ee30b29cdc4c6dad4c7f06965f6b6e2a85eae34b49ac0b144f471",
    "RepoTags": [],
    "Created": "2022-01-11T18:25:40.371645323Z",
    "DockerVersion": "20.10.12",
    "Labels": null,
    "Architecture": "amd64",
    "Os": "linux",
    "Layers": [
        "sha256:72a69066d2febc34d8f3dbcb645f7b851a57e9681322ece7ad8007503b783c19",
        "sha256:55021ef4630b6895c6f61c7119aaa045b403811902f09ac02faabdedf70ac9e8",
        "sha256:7b87c002c0119958e56d51615d51f2702fa12f6662c9286b2280b51e2b3953cf"
    ],
    "Env": [
        "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
        "GRPC_GO_LOG_SEVERITY_LEVEL=INFO"
    ]
}
```

**Comment by marquiz** [comment]
Github release page:
https://github.com/kubernetes-sigs/node-feature-discovery/releases/tag/v0.10.0
